### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by CandyYoung** [plutext/Docx4j4Android4#2]
Environment: android studio 2.3
Part of error log:
Error:Uncaught translation error: java.lang.IllegalArgumentException: already added: Lorg/slf4j/ILoggerFactory;
Error:Uncaught translation error: java.lang.IllegalArgumentException: already added: Lorg/slf4j/IMarkerFactory;
Error:Uncaught translation error: java.lang.IllegalArgumentException: already added: Lorg/slf4j/Logger;
Error:Uncaught translation error: java.lang.IllegalArgumentException: already added: Lorg/slf4j/LoggerFactory;
Error:Uncaught translation error: java.lang.IllegalArgumentException: already added: Lorg/slf4j/MDC;
Error:Uncaught translation error: java.lang.IllegalArgumentException: already added: Lorg/slf4j/Marker;
Error:Uncaught translation error: java.lang.IllegalArgumentException: already added: Lorg/slf4j/MarkerFactory;
Error:Uncaught translation error: java.lang.IllegalArgumentException: already added: Lorg/slf4j/helpers/BasicMDCAdapter;
Error:Uncaught translation error: java.lang.IllegalArgumentException: already added: Lorg/slf4j/helpers/BasicMarker;
Error:Error converting bytecode to dex:
Cause: java.lang.RuntimeException: Translation has been interrupted

**Comment by zk0301** [comment]
the same as me. build failed .

**Comment by spudi** [comment]
+1 the same

**Comment by plutext** [comment]
Please try with latest commits, at https://github.com/plutext/Docx4j4Android4/commit/cdc9bbdc004f4d62c65fb877715ff06039ad5207

If you continue to have issues, please open a new one.
